#!/bin/bash

# Copie tous les .cpp, .cppm, .hpp avec encadrement Markdown
  (find ./srcs/ -type f  -name "*.cpp" -o -name "*.cppm" -o -name "*.hpp" -o -name "Makefile"  | while read -r file; do
    echo "$(basename "$file"):"
    echo "\`\`\`cpp"
    echo ""
    cat "$file"
    echo ""
    echo "\`\`\`"
    echo ""
done ) | wl-copy
